### ISSUE TITLE
Graphical glitch in tabs

### ISSUE THREAD

**Issue by okoetter** [mark-hahn/command-toolbar#2]
Hi there,
I have a graphical glitch in my tab bar, see attached image: A horizontal dark line going through the tab bar.

![glitch](https://cloud.githubusercontent.com/assets/4048240/5501970/5b407014-8763-11e4-95a1-d55d7b8fb232.png)

I am not sure if this package is responsible, but the line is gone if I disable command toolbar.

- Atom 0.162.0 on Windows
- UI Theme: Atom Dark, but others don't help
- Syntax Theme: Monokai, but others don't help

**Comment by DinisCruz** [comment]
I'm also having this issue 
![image](https://cloud.githubusercontent.com/assets/656739/5683549/b30c35e4-9820-11e4-99e8-f4c0897a77a4.png)

**Comment by mark-hahn** [comment]
I traced this down to a problem in the tab-bar module.  See https://github.com/atom/tabs/issues/105.  Please follow that for progress on the problem.

**Comment by mark-hahn** [comment]
This will be fixed in Atom release 170.

**Comment by okoetter** [comment]
I can confirm that this is fixed in Atom 0.170.0

**Comment by mark-hahn** [comment]
Apparently there aren't too many packages that go on the top panel.
Anything on top had this problem.
